import * as pdfjsLib from 'pdfjs-dist'
import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url'

// Set the workerSrc to the locally bundled worker asset generated by Vite
pdfjsLib.GlobalWorkerOptions.workerSrc = pdfjsWorker

export { pdfjsLib }
